name: Test

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: echo 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit' >> $env:GITHUB_PATH
      - run: makeappx.exe

