name: Test

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      KIT_PATH: 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit'
    steps:
      - run: echo $env:KIT_PATH >> $env:GITHUB_PATH
      - run: makeappx.exe

